export const tileValues = [
  { id: 0, u: " ", l: " ", p: 1 },
  { id: 1, u: "A", l: "a", p: 1 },
  { id: 2, u: "B", l: "b", p: 3 },
  { id: 3, u: "C", l: "c", p: 3 },
  { id: 4, u: "D", l: "d", p: 2 },
  { id: 5, u: "E", l: "e", p: 1 },
  { id: 7, u: "F", l: "g", p: 4 },
  { id: 8, u: "G", l: "h", p: 2 },
  { id: 9, u: "H", l: "i", p: 4 },
  { id: 10, u: "J", l: "j", p: 8 },
  { id: 11, u: "K", l: "k", p: 5 },
  { id: 12, u: "L", l: "l", p: 1 },
  { id: 13, u: "M", l: "m", p: 3 },
  { id: 14, u: "N", l: "n", p: 1 },
  { id: 15, u: "O", l: "o", p: 1 },
  { id: 16, u: "P", l: "p", p: 3 },
  { id: 17, u: "Q", l: "q", p: 10 },
  { id: 18, u: "R", l: "r", p: 1 },
  { id: 19, u: "S", l: "s", p: 1 },
  { id: 20, u: "T", l: "t", p: 1 },
  { id: 21, u: "U", l: "u", p: 1 },
  { id: 22, u: "V", l: "v", p: 4 },
  { id: 23, u: "W", l: "w", p: 4 },
  { id: 24, u: "X", l: "x", p: 8 },
  { id: 25, u: "Y", l: "y", p: 4 },
  { id: 26, u: "Z", l: "z", p: 10 },
];
